syntax = "proto2";

package earth.document.protos;

import "geo/earth/proto/contentcreation/data_import_errors.proto";
import "geo/earth/proto/earth_mate/earth_mate_error_detail.proto";
import "net/proto2/bridge/proto/message_set.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "com.google.geo.earth.errors";

message ErrorResponse {
    optional ErrorId error_id = 1 [default = UNKNOWN_ERROR_ID];
    enum ErrorId {
        UNKNOWN_ERROR_ID = 0;
        INTERNAL_ERROR = 1;
        NOT_FOUND = 2;
        PERMISSION_DENIED = 3;
        INVALID_GEOMETRY_IN_S2 = 4;
        MAX_LAYERS_REACHED = 5;
        QUOTA_EXCEEDED = 6;
        DATA_IMPORT_ERROR = 7;
        EARTH_MATE_ERROR = 8;
    }
    
    optional bool is_retryable = 2 [default = false];
    optional string message = 3;
    optional bool throttled = 5 [default = false];
    
    oneof detailed_error {
        DataImportErrorStatus data_import_error_status = 4;
        geo.earth.proto.earth_mate.EarthMateErrorDetail earth_mate_error_detail = 6;
    }
    
    extend .proto2.bridge.MessageSet {
        optional ErrorResponse message_set_extension = 151616216;
    }
}
